name = 'rust'

[Colors]
base = [51, 29, 44, 255]
background = [63, 46, 62, 255]
accent = [167, 130, 149, 255]
highlight = [239, 225, 209, 255]

[Text]
[Text.Normal]
name = "monofur"
path = "font/monof55.ttf"
size = 12
[Text.Header]
name = "monofur"
path = "font/monof55.ttf"
size = 20

[Editor]
point_radius = 3
line_thickness = 2
padding = 2

[Editor.Colors]
block = 'base'
background = 'background'
accent = 'accent'
connection = 'highlight'
select = 'highlight'

[Editor.Block]
radius = 12
header = 24
footer = 12
select = 16