[Config]
name = ""
blocks = false
connections = false

[Blocks]

[[Blocks.Variables]]
name = ""
inputs = {}
outputs = {}


[[Blocks.Data]]
type = ""
uid = ""
config = {}
position = []


[Connections]
[[Connections.Data]]
uid = ""
source = ""
output = ""
target = ""
input = ""
