from .core import Element


class NestedImplementationElement(Element):...
class ConnectionNodeElement(Element):...
class ValueInputElemnet(Element):...
class BlockElement(Element):...
class TempValueElement(Element):...